dataset_build_config: configs/dataset/sberquad_base.yaml
positive_generation_config: configs/dataset/sberquad_positive_generation.yaml
passage_generation_config: configs/dataset/sberquad_promptriever_passages.yaml
dataset_assembly_config: configs/dataset/sberquad_promptriever_dataset.yaml
train_config: configs/train/e5_promptriever.yaml
rumteb_eval_config: configs/eval/rumteb_russian.yaml
mfollowir_eval_config: configs/eval/mfollowir_russian.yaml
